### ISSUE TITLE
City names with non-ASCII characters cause failures in Car2Go API calls

### ISSUE THREAD

**Issue by eebbesen** [eebbesen/freerider_api#18]
København and München have characters that need to be encoded for API calls

```
Finished processing 711 vehicles for Hamburg
Processing vehicle locations for K\xC3\xB8benhavn
rake aborted!
OpenURI::HTTPError: 400 Bad Request
/Users/eebbesen/.rvm/gems/ruby-2.2.2@frapi/gems/caruby2go-0.0.2/lib/caruby2go.rb:39:in `issue_get'
/Users/eebbesen/.rvm/gems/ruby-2.2.2@frapi/gems/caruby2go-0.0.2/lib/caruby2go.rb:28:in `vehicles'
/Users/eebbesen/proj3/fr_api/app/controllers/vehicle_locations_controller.rb:52:in `poll_and_persist'
/Users/eebbesen/proj3/fr_api/lib/tasks/scheduler.rake:10:in `block (2 levels) in <top (required)>'
/Users/eebbesen/proj3/fr_api/lib/tasks/scheduler.rake:5:in `each'
/Users/eebbesen/proj3/fr_api/lib/tasks/scheduler.rake:5:in `block in <top (required)>'
Tasks: TOP => poll_and_persist_vehicles
(See full trace by running task with --trace)
```

**Comment by eebbesen** [comment]
`URI.encode '<city_name>'`
